/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EscotistaRouteRouteImport } from './routes/escotista/route'
import { Route as EspecialidadesRouteImport } from './routes/especialidades'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as RevisaoRapidaRouteImport } from './routes/revisao-rapida'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as EscotistaIndexRouteImport } from './routes/escotista/index'
import { Route as EscotistaAdminRouteImport } from './routes/escotista/admin'
import { Route as EscotistaPendingRouteImport } from './routes/escotista/pending'
import { Route as EscotistaStatsRouteImport } from './routes/escotista/stats'
import { Route as EscotistaTimelineRouteImport } from './routes/escotista/timeline'
import { Route as EscotistaEscoteiroEscoteiroIdRouteImport } from './routes/escotista/escoteiro.$escoteiroId'
import { Route as EscotistaEspecialidadesIndexRouteImport } from './routes/escotista/especialidades.index'
import { Route as EscotistaEspecialidadesSpecialtyIdRouteImport } from './routes/escotista/especialidades.$specialtyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EscotistaRouteRoute = EscotistaRouteRouteImport.update({
  id: '/escotista',
  path: '/escotista',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialidadesRoute = EspecialidadesRouteImport.update({
  id: '/especialidades',
  path: '/especialidades',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisaoRapidaRoute = RevisaoRapidaRouteImport.update({
  id: '/revisao-rapida',
  path: '/revisao-rapida',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EscotistaIndexRoute = EscotistaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EscotistaRouteRoute,
} as any)
const EscotistaAdminRoute = EscotistaAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => EscotistaRouteRoute,
} as any)
const EscotistaPendingRoute = EscotistaPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => EscotistaRouteRoute,
} as any)
const EscotistaStatsRoute = EscotistaStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => EscotistaRouteRoute,
} as any)
const EscotistaTimelineRoute = EscotistaTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => EscotistaRouteRoute,
} as any)
const EscotistaEscoteiroEscoteiroIdRoute =
  EscotistaEscoteiroEscoteiroIdRouteImport.update({
    id: '/escoteiro/$escoteiroId',
    path: '/escoteiro/$escoteiroId',
    getParentRoute: () => EscotistaRouteRoute,
  } as any)
const EscotistaEspecialidadesIndexRoute =
  EscotistaEspecialidadesIndexRouteImport.update({
    id: '/especialidades/',
    path: '/especialidades/',
    getParentRoute: () => EscotistaRouteRoute,
  } as any)
const EscotistaEspecialidadesSpecialtyIdRoute =
  EscotistaEspecialidadesSpecialtyIdRouteImport.update({
    id: '/especialidades/$specialtyId',
    path: '/especialidades/$specialtyId',
    getParentRoute: () => EscotistaRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/escotista': typeof EscotistaRouteRouteWithChildren
  '/especialidades': typeof EspecialidadesRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/revisao-rapida': typeof RevisaoRapidaRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/escotista/admin': typeof EscotistaAdminRoute
  '/escotista/pending': typeof EscotistaPendingRoute
  '/escotista/stats': typeof EscotistaStatsRoute
  '/escotista/timeline': typeof EscotistaTimelineRoute
  '/escotista/': typeof EscotistaIndexRoute
  '/escotista/escoteiro/$escoteiroId': typeof EscotistaEscoteiroEscoteiroIdRoute
  '/escotista/especialidades/$specialtyId': typeof EscotistaEspecialidadesSpecialtyIdRoute
  '/escotista/especialidades/': typeof EscotistaEspecialidadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/especialidades': typeof EspecialidadesRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/revisao-rapida': typeof RevisaoRapidaRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/escotista/admin': typeof EscotistaAdminRoute
  '/escotista/pending': typeof EscotistaPendingRoute
  '/escotista/stats': typeof EscotistaStatsRoute
  '/escotista/timeline': typeof EscotistaTimelineRoute
  '/escotista': typeof EscotistaIndexRoute
  '/escotista/escoteiro/$escoteiroId': typeof EscotistaEscoteiroEscoteiroIdRoute
  '/escotista/especialidades/$specialtyId': typeof EscotistaEspecialidadesSpecialtyIdRoute
  '/escotista/especialidades': typeof EscotistaEspecialidadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/escotista': typeof EscotistaRouteRouteWithChildren
  '/especialidades': typeof EspecialidadesRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/revisao-rapida': typeof RevisaoRapidaRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/escotista/admin': typeof EscotistaAdminRoute
  '/escotista/pending': typeof EscotistaPendingRoute
  '/escotista/stats': typeof EscotistaStatsRoute
  '/escotista/timeline': typeof EscotistaTimelineRoute
  '/escotista/': typeof EscotistaIndexRoute
  '/escotista/escoteiro/$escoteiroId': typeof EscotistaEscoteiroEscoteiroIdRoute
  '/escotista/especialidades/$specialtyId': typeof EscotistaEspecialidadesSpecialtyIdRoute
  '/escotista/especialidades/': typeof EscotistaEspecialidadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/escotista'
    | '/especialidades'
    | '/onboarding'
    | '/plan'
    | '/revisao-rapida'
    | '/settings'
    | '/signin'
    | '/trocar-senha'
    | '/escotista/admin'
    | '/escotista/pending'
    | '/escotista/stats'
    | '/escotista/timeline'
    | '/escotista/'
    | '/escotista/escoteiro/$escoteiroId'
    | '/escotista/especialidades/$specialtyId'
    | '/escotista/especialidades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/especialidades'
    | '/onboarding'
    | '/plan'
    | '/revisao-rapida'
    | '/settings'
    | '/signin'
    | '/trocar-senha'
    | '/escotista/admin'
    | '/escotista/pending'
    | '/escotista/stats'
    | '/escotista/timeline'
    | '/escotista'
    | '/escotista/escoteiro/$escoteiroId'
    | '/escotista/especialidades/$specialtyId'
    | '/escotista/especialidades'
  id:
    | '__root__'
    | '/'
    | '/escotista'
    | '/especialidades'
    | '/onboarding'
    | '/plan'
    | '/revisao-rapida'
    | '/settings'
    | '/signin'
    | '/trocar-senha'
    | '/escotista/admin'
    | '/escotista/pending'
    | '/escotista/stats'
    | '/escotista/timeline'
    | '/escotista/'
    | '/escotista/escoteiro/$escoteiroId'
    | '/escotista/especialidades/$specialtyId'
    | '/escotista/especialidades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EscotistaRouteRoute: typeof EscotistaRouteRouteWithChildren
  EspecialidadesRoute: typeof EspecialidadesRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  RevisaoRapidaRoute: typeof RevisaoRapidaRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escotista': {
      id: '/escotista'
      path: '/escotista'
      fullPath: '/escotista'
      preLoaderRoute: typeof EscotistaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialidades': {
      id: '/especialidades'
      path: '/especialidades'
      fullPath: '/especialidades'
      preLoaderRoute: typeof EspecialidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisao-rapida': {
      id: '/revisao-rapida'
      path: '/revisao-rapida'
      fullPath: '/revisao-rapida'
      preLoaderRoute: typeof RevisaoRapidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escotista/': {
      id: '/escotista/'
      path: '/'
      fullPath: '/escotista/'
      preLoaderRoute: typeof EscotistaIndexRouteImport
      parentRoute: typeof EscotistaRouteRoute
    }
    '/escotista/admin': {
      id: '/escotista/admin'
      path: '/admin'
      fullPath: '/escotista/admin'
      preLoaderRoute: typeof EscotistaAdminRouteImport
      parentRoute: typeof EscotistaRouteRoute
    }
    '/escotista/pending': {
      id: '/escotista/pending'
      path: '/pending'
      fullPath: '/escotista/pending'
      preLoaderRoute: typeof EscotistaPendingRouteImport
      parentRoute: typeof EscotistaRouteRoute
    }
    '/escotista/stats': {
      id: '/escotista/stats'
      path: '/stats'
      fullPath: '/escotista/stats'
      preLoaderRoute: typeof EscotistaStatsRouteImport
      parentRoute: typeof EscotistaRouteRoute
    }
    '/escotista/timeline': {
      id: '/escotista/timeline'
      path: '/timeline'
      fullPath: '/escotista/timeline'
      preLoaderRoute: typeof EscotistaTimelineRouteImport
      parentRoute: typeof EscotistaRouteRoute
    }
    '/escotista/escoteiro/$escoteiroId': {
      id: '/escotista/escoteiro/$escoteiroId'
      path: '/escoteiro/$escoteiroId'
      fullPath: '/escotista/escoteiro/$escoteiroId'
      preLoaderRoute: typeof EscotistaEscoteiroEscoteiroIdRouteImport
      parentRoute: typeof EscotistaRouteRoute
    }
    '/escotista/especialidades/': {
      id: '/escotista/especialidades/'
      path: '/especialidades'
      fullPath: '/escotista/especialidades/'
      preLoaderRoute: typeof EscotistaEspecialidadesIndexRouteImport
      parentRoute: typeof EscotistaRouteRoute
    }
    '/escotista/especialidades/$specialtyId': {
      id: '/escotista/especialidades/$specialtyId'
      path: '/especialidades/$specialtyId'
      fullPath: '/escotista/especialidades/$specialtyId'
      preLoaderRoute: typeof EscotistaEspecialidadesSpecialtyIdRouteImport
      parentRoute: typeof EscotistaRouteRoute
    }
  }
}

interface EscotistaRouteRouteChildren {
  EscotistaAdminRoute: typeof EscotistaAdminRoute
  EscotistaPendingRoute: typeof EscotistaPendingRoute
  EscotistaStatsRoute: typeof EscotistaStatsRoute
  EscotistaTimelineRoute: typeof EscotistaTimelineRoute
  EscotistaIndexRoute: typeof EscotistaIndexRoute
  EscotistaEscoteiroEscoteiroIdRoute: typeof EscotistaEscoteiroEscoteiroIdRoute
  EscotistaEspecialidadesSpecialtyIdRoute: typeof EscotistaEspecialidadesSpecialtyIdRoute
  EscotistaEspecialidadesIndexRoute: typeof EscotistaEspecialidadesIndexRoute
}

const EscotistaRouteRouteChildren: EscotistaRouteRouteChildren = {
  EscotistaAdminRoute: EscotistaAdminRoute,
  EscotistaPendingRoute: EscotistaPendingRoute,
  EscotistaStatsRoute: EscotistaStatsRoute,
  EscotistaTimelineRoute: EscotistaTimelineRoute,
  EscotistaIndexRoute: EscotistaIndexRoute,
  EscotistaEscoteiroEscoteiroIdRoute: EscotistaEscoteiroEscoteiroIdRoute,
  EscotistaEspecialidadesSpecialtyIdRoute:
    EscotistaEspecialidadesSpecialtyIdRoute,
  EscotistaEspecialidadesIndexRoute: EscotistaEspecialidadesIndexRoute,
}

const EscotistaRouteRouteWithChildren = EscotistaRouteRoute._addFileChildren(
  EscotistaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EscotistaRouteRoute: EscotistaRouteRouteWithChildren,
  EspecialidadesRoute: EspecialidadesRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  RevisaoRapidaRoute: RevisaoRapidaRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
